# Generated by Django 5.2.17 on 2026-09-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispense', to='records.prescription'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['name', 'strength'], name='pharmacy_me_name_6f820d_idx'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medication'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses', to='pharmacy.stockbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='stockbatch',
            unique_together={('medication', 'batch_number')},
        ),
    ]
